#!/bin/sh
#
# Steps to deploy the service to a target box:
#
# - on a source box:
#     scp ./ctl <target>:~/
#     scp -r ./opt/ctl <target>:~/opt
#
# - on a target box:
#     sudo cp ~/ctl /etc/init.d

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides:          ctl
# Required-Start:    $remote_fs $syslog $time$network
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript to spawn ctlService.sh as alec
# Description:       Spawns a daemon to support Cloud Trust configuration process.
#                    Based off of /etc/init.d/skeleton file.
### END INIT INFO

# Author: Alec Missine <support@minetats.com>

DESC="Configuration process support for distributed applications, (c) 2017 Cloud Trust, Ltd. All rights reserved."
DAEMON=/home/alec/opt/ctl/ctlService.sh
