#!/usr/bin/env bash

declare logfile="/tmp/lnet.log" pipe="/tmp/lnet"
LNET_HOME="$(dirname $0)"
lnet_run="$LNET_HOME/bin/run.js"

log() {
  local f='-Ins' timestamp=$([ `uname` == "Darwin" ] && gdate $f || date $f)
  echo "$timestamp $1" >> $logfile
}

log "Started $0 with $# arguments LNET_HOME=$LNET_HOME"
[ $# -eq 0 ] && { $lnet_run; log "Stopped $0"; exit 0; }

log "Arguments: $@"
[ -p $pipe ] && rm $pipe
mkfifo $pipe
$1 < $pipe | $lnet_run > $pipe
log "Stopped $0"
