#!/bin/sh

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides:          ctl
# Required-Start:    $remote_fs $syslog $time $network
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript to spawn ctlService.sh
# Description:       Spawns a daemon to support Cloud Trust Ltd distribution process.
#                    Based off of /etc/init.d/skeleton file.
### END INIT INFO

# Author: Alec Missine <support@minetats.com>

CTLNAME=@CTLNAME@
CTL_HOME=/home/$CTLNAME
DESC="Distribution process support for Cloud Trust Ltd"
DAEMON=$CTL_HOME/distro/ctl/ctlService.sh

do_stop_cleanup() {
  local pipe="/tmp/$CTLNAME"
  echo "exit" >> $pipe
}