#!/bin/sh
#
# TODO: update the comments below
# Steps to manually deploy the service to a target box for the first time:
#
# - on a source box:
#     cd ~/project/lnet/test/rc/05
#     tar -czvf distro.tar.gz distro
#     scp distro.tar.gz <target>:~/ # and, when the target box is ready:
#     ssh <target> echo "distro copied" >> /tmp/ctl
#
# - on a target box:
#     cd ~/
#     tar -xzvf distro.tar.gz
#     sudo distro/ctl/ctlService.sh # and then echo "distro updated" >> /tmp/ctl from the source box

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides:          ctl
# Required-Start:    $remote_fs $syslog $time $network
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript to spawn ctlService.sh
# Description:       Spawns a daemon to support Cloud Trust configuration process.
#                    Based off of /etc/init.d/skeleton file.
### END INIT INFO

# Author: Alec Missine <support@minetats.com>

CTL_HOME=/home/alec
DESC="Configuration process support for distributed applications. Copyright (c) 2017 Cloud Trust, Ltd. All rights reserved."
DAEMON=$CTL_HOME/distro/ctl/ctlService.sh
