#!/bin/sh
#
# Copyright 2017 Alec Missine (support@minetats.com) 
#                and the Arbitrage Logistics International (ALI) project
#
# The ALI Project licenses this file to you under the Apache License, version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# === /etc/init.d/$CTLSVC_NAME ===
# Start ctlsvc daemon
#
# See also:
#   https://docs.google.com/document/d/1JPzTa7IXEQL0NZLoO5leCNj40e7yy1dFNMiqTtBNH2o/

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

### BEGIN INIT INFO
# Provides:          ctl
# Required-Start:    $remote_fs $syslog $time $network
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript to spawn ctlsvc.sh
# Description:       Spawns a daemon to support Cloud Trust Ltd distribution process.
#                    Based off of /etc/init.d/skeleton file.
### END INIT INFO

# Author: Alec Missine <support@minetats.com>

CTLSVC_ACCOUNT=@CTLSVC_ACCOUNT@
CTLSVC_NAME="ctlsvc_$CTLSVC_ACCOUNT"
CTLSVC_ACCOUNT_HOME=/home/$CTLSVC_ACCOUNT
DESC="Distribution process support for Cloud Trust Ltd"
DAEMON=$CTLSVC_ACCOUNT_HOME/ctlsvc_distro/ctlsvc.sh

do_stop_cleanup() {
  local pipe="/tmp/$CTLSVC_NAME"
  echo "exit" >> $pipe
}
